start_lr = 3e-5
train_bs = 16
valid_bs = 16
epochs = 5
max_len = 128
dropout_ratio = 0.3
linear_in = 768
num_classes = 2
warmup_epochs = 1
test_size = 0.25
train_file ='./train.csv'
test_file = './test.csv'
model_name = 'bert-base-uncased'