start_lr = 3e-5
train_bs = 8
valid_bs = 4
epochs = 5
max_len = 160
dropout_ratio = 0.0
linear_in = 768
num_classes = 2
warmup_epochs = 0
test_size = 0.2
train_file ='./train.csv'
test_file = './test.csv'
model_name = 'bert-base-uncased'
seed = 10
use_sched = False